//! Generate the development Groth16 verifying key as a Rust source module for
//! the on-chain program.
//!
//! Usage:
//! ```bash
//! cargo run -p mp-proof --example gen_vk > programs/mirror_pool/src/vk.rs
//! cargo fmt --all
//! ```

use ark_std::rand::{rngs::StdRng, SeedableRng};
use mp_proof::proving::setup;
use mp_proof::solana::vk_to_bytes;
use mp_proof::{DEV_SETUP_SEED, TREE_HEIGHT};

fn bytes(b: &[u8]) -> String {
    b.iter()
        .map(|x| x.to_string())
        .collect::<Vec<_>>()
        .join(", ")
}

fn main() {
    let mut rng = StdRng::seed_from_u64(DEV_SETUP_SEED);
    let (_pk, vk) = setup(TREE_HEIGHT, &mut rng);
    let vk = vk_to_bytes(&vk);
    let n = vk.ic.len();

    println!("//! GENERATED by `cargo run -p mp-proof --example gen_vk` — do not edit by hand.");
    println!("//!");
    println!("//! Development Groth16 verifying key for the `S_propose` circuit");
    println!("//! (tree height {TREE_HEIGHT}, dev setup seed {DEV_SETUP_SEED}).");
    println!("//!");
    println!("//! NOT FOR PRODUCTION: replace with keys from a trusted-setup ceremony");
    println!("//! (`docs/ROADMAP.md` §5).");
    println!();
    println!("use groth16_solana::groth16::Groth16Verifyingkey;");
    println!();
    println!("pub const VK_ALPHA_G1: [u8; 64] = [{}];", bytes(&vk.alpha));
    println!("pub const VK_BETA_G2: [u8; 128] = [{}];", bytes(&vk.beta));
    println!("pub const VK_GAMMA_G2: [u8; 128] = [{}];", bytes(&vk.gamma));
    println!("pub const VK_DELTA_G2: [u8; 128] = [{}];", bytes(&vk.delta));
    println!("pub const VK_IC: [[u8; 64]; {n}] = [");
    for point in &vk.ic {
        println!("[{}],", bytes(point));
    }
    println!("];");
    println!();
    println!("/// The development verifying key, for `groth16-solana`.");
    println!("pub fn verifying_key() -> Groth16Verifyingkey<'static> {{");
    println!("    Groth16Verifyingkey {{");
    println!("        nr_pubinputs: {n},");
    println!("        vk_alpha_g1: VK_ALPHA_G1,");
    println!("        vk_beta_g2: VK_BETA_G2,");
    println!("        vk_gamme_g2: VK_GAMMA_G2,");
    println!("        vk_delta_g2: VK_DELTA_G2,");
    println!("        vk_ic: &VK_IC,");
    println!("    }}");
    println!("}}");
}
